services:
  stock-predictor-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-predictor-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app/models:/app/app/models
    restart: unless-stopped
