services:
  stock-predictor-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-predictor-api
    ports:
      - "8000:8000"
    environment:
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY:-}
    volumes:
      - ./app/models:/app/app/models
    restart: unless-stopped
